FROM ubuntu
RUN apt-get -y update
RUN apt-get -y install python
RUN apt-get -y install g++
RUN apt-get -y install gcc
RUN apt-get -y install default-jre
RUN apt-get -y install default-jdk
WORKDIR /tmp