# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 10:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem_name', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('constraints', models.TextField()),
                ('time_limit', models.IntegerField(default=1)),
                ('sample_ip', models.TextField()),
                ('sample_op', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('lang_id', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('tc_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.TextField()),
                ('op', models.TextField()),
                ('score', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.Question')),
            ],
        ),
        migrations.AddField(
            model_name='submissionresults',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.Submissions'),
        ),
        migrations.AddField(
            model_name='submissionresults',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.TestCase'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionresults',
            unique_together=set([('testcase', 'submission')]),
        ),
    ]
