# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
